### ISSUE TITLE
Ability to mark that room has no video

### ISSUE THREAD

**Issue by ldang** [socallinuxexpo/scale-av-cutter#1]
Could we have an option to mark that

a) room was not recorded.  No video exists
b) room was recorded, but video is bad
c) room was recorded, but video is not on Youtube (or easily accessible).  See comment.

Lowest hanging fruit is to indicate that video is N/A , so I don't have to figure out why we aren't listing video for a talk.

**Comment by EaterOA** [comment]
Most generic and flexible is probably offer a freeform note field. Maybe an additional admin-only note field also, but I'm just overengineering now.

**Comment by EaterOA** [comment]
Added comment field that can be set by admin in index page.
