### ISSUE TITLE
webapp: Would like more categories than Incomplete/Done/Unusable

### ISSUE THREAD

**Issue by ldang** [socallinuxexpo/scale-av-cutter#11]
I think the webapp would be a good record of past talks and why the videos exist or don't exist.

Thinking ahead to additional categories to label the talks.

1) Unusable due to video quality
   - audio is bad
   - video is bad
   - it's missing chunks or cut-off.

2) Unusable because it is a BoF
  - maybe we could filter the BoFs out of the list of talks that the web app recognizes

3) Don't publish 
 
4) Need manual editing

**Comment by EaterOA** [comment]
What is BoF?
Considering adding a notes field to each talk, then it's infinitely flexible. Unusable will be catch-all status, ideally with notes explaining why.

**Comment by EaterOA** [comment]
Ok, there's a notes field for each talk now. Editable by any role until cut is approved, then only editable by reviewers and admins.
