### ISSUE TITLE
Easy way to specify thumbnail and upload it

### ISSUE THREAD

**Issue by destevae** [socallinuxexpo/scale-av-cutter#27]
Right now, thumbnails are manually screenshotted and uploaded on Youtube. 

Potential fix ideas include:

- Ability to tag a particular scene to be a thumbnail in the web app and add overlay text onto the image and use it to upload onto Youtube.
- Programmatically generate a thumbnail from speaker images and the talk title and then overlay a transparent thumbnail moment from the video. Then upload the image onto Youtube.

**Comment by ldang** [comment]
Really interested in having you explore this and let us know if it's easy to do.   I think you can start out by seeing how to optionally upload to YouTube with a thumbnail, and then work backwards from that to generating the thumbnail.
