### ISSUE TITLE
Help message for editors and reviewers

### ISSUE THREAD

**Issue by destevae** [socallinuxexpo/scale-av-cutter#33]
The help message would include recommendations for how to edit/review the videos.

**Comment by ldang** [comment]
This would require communicating with the people who edit and review the videos...so @Secret-Asian-Man (who did most of the reviewing last year) and @destevae coudl work together on this.

**Comment by Secret-Asian-Man** [comment]
It would be more streamlined for new editors/reviewers if we embed job info throughout the cutter.

Add job description to main page.
![image](https://github.com/socallinuxexpo/scale-av-cutter/assets/10111681/fdf879ba-8994-4653-bd4f-4fed89b42b00)



Add tooltips/titles to widgets.
![ScaleAVCutter (2)](https://github.com/socallinuxexpo/scale-av-cutter/assets/10111681/7f4e0c12-d30c-4411-9ec8-581e84a1b172)

**Comment by destevae** [comment]
Those look like good ideas! I'll implement them. @Secret-Asian-Man are you able to write up a short job description for reviewers too? Thanks.
